---
title: "Add 5 Prime Contig Data to H5 Metadata"
author: 
 - Qiuyu Gong ; Lucas Graybuck
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output:
  html_document:
    code_folding: hide
    df_print: paged
    self_contained: true
params:
  in_h5: NULL
  in_category: NULL
  out_dir: NULL
---

<a id="contents"></a>

## Contents



#### [Session Info](#session_info)

<a id="data_processing"></a>

## Data Processing

<a id="session_preparation"></a>

### Session Preparation


#### Load libraries:
```{r Load Libraries}
start_time <- Sys.time()

quiet_library <- function(...) {
  suppressPackageStartupMessages(library(...))
}
quiet_library(rhdf5)
quiet_library(H5weaver)
quiet_library(Matrix)
quiet_library(tidyr)
quiet_library(cowplot)
quiet_library(jsonlite)
quiet_library(stringr)
quiet_library(reshape)
quiet_library(stringi)
quiet_library(Seurat)

```

```{r Declare start}
stm("Starting Adding Contig data into H5 metadata")
```

Argument Parsing  
```{r parse_arguments}
# give input directory rna-specific name 
if(is.null(params$in_dir)) {
  in_dir <- system.file("extdata/X070", package = "tenx_vdj_pipeline")
  in_key <- system.file("extdata/example_sample_key_X070.csv", package = "tenx_vdj_pipeline")
  in_config <- system.file("extdata/default_rna_config_v1.csv", package = "tenx_vdj_pipeline")
  out_dir <- tempdir()
} else {
  in_h5 <- params$in_h5  
  in_h5 <- params$in_contig
  in_category <- params$in_category  
  out_dir <- params$out_dir
  in_batch<- params$in_batch
  
}



stm(paste0("IN H5    : ", in_h5))
stm(paste0("IN Contig    : ", in_contig))
stm(paste0("IN Category   : ", in_category))
stm(paste0("OUT Dir        : ", out_dir))
stm(paste0("Batch ID        : ", in_batch))

print(paste0("IN H5        : ", in_h5))
print(paste0("IN Contig    : ", in_contig))
print(paste0("IN Category       : ", in_category))
print(paste0("OUT Dir         : ", out_dir))
print(paste0("Batch ID        : ", in_batch))

```  



Check input files  
```{r check_input_main}
if(!file.exists(in_h5)) {
  stm(paste("ERROR: Cannot find IN H5:", in_h5))
  stop()
}
if(!file.exists(in_contig)) {
  stm(paste("ERROR: Cannot find IN Contig:", in_contig))
  stop()
}

if(!dir.exists(out_dir)) {
  stm(paste("Creating output directory:", out_dir))
  dir.create(out_dir)
}

batch_id<-in_batch
out_prefix <- file.path(out_dir, paste0(batch_id, "_"))

```








[Return to Contents](#contents)

<a id="session_info"></a>

## Session Information

```{r Session Info}
sessionInfo()
```

Total time elapsed
```{r Show Time}
end_time <- Sys.time()
diff_time <- end_time - start_time
time_message <- paste0("Elapsed Time: ", 
                       round(diff_time, 3),
                       " ", units(diff_time))
print(time_message)
stm(time_message)
stm("H5 metadata process complete.")
```

[Return to Contents](#contents)
